# Generated by Django 5.1.4 on 2025-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profiles/user.png', null=True, upload_to='images/profiles'),
        ),
    ]
